### PR TITLE
added monitoring of the battery usage and state

### PR DESCRIPTION
**Pull request by Sim4n6**

### CODE REVIEW

**Comment by atarallo** [comment]
I'm not sure of adding this feature. It's very useful for laptops. But has no sense on servers, at least for me this script has no sense on desktops/laptops.

**Comment by Sim4n6** [comment]
Right, not useful on servers, don't add it ok

**Comment by atarallo** [comment]
I'm not closed to adding this. I'm trying to figure out if it's useful.  I've also noticed that in the server I have on hand (SuSE Enterprise Server) is not installed. 

Maybe adding a check (as we do with curl) could make sense. Please let me know what do you think about this.

**Comment by Sim4n6** [comment]
No need to add it, you were right. The script is for servers. As a tip, the script can be runned when the admin connect via ssh. Let's keep it like that

**Pull request closed without merging**
